apiVersion: v1
kind: Service
metadata:
   name: myservice
   labels: 
      app: myapp
spec:
   type: NodePort
   ports: 
      - nodePort: 32003
        port: 9000
        targetPort: 80
   selector:
      app: myapp
